# ==============================================================================
# Play/Evaluation Mode Layer
# ==============================================================================
# Applied for teacher play/evaluation.
# Harder waypoints, max curriculum, basic visualization.
# ==============================================================================

# Start at max difficulty
curriculum:
  difficulty:
    initial: 1

# Basic visualization
visualization:
  targets: false
  current_object: false
  pose_axes: true
  env_ids: null
  debug_print_rewards: false
  hand_pose_targets: true
  grasp_surface_point: false 
  contact_forces: true

# Fewer envs for visualization
simulation:
  num_envs: 2

procedural_objects:
  generation:
    num_shapes: 10  