asset_path: /home/harsh/sam/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/manager_based/manipulation/y2r/assets/ur5e_leap/ur5e_leap_right_gemini305.urdf
usd_dir: /home/harsh/sam/IsaacLab/source/isaaclab_tasks/isaaclab_tasks/manager_based/manipulation/y2r/assets/ur5e_leap/ur5e_leap_right_gemini305_usd
usd_file_name: null
force_usd_conversion: false
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: null
    damping: null
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: true
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: 0.0
  angular_damping: 0.0
  max_linear_velocity: 1000.0
  max_angular_velocity: 1000.0
  max_depenetration_velocity: 1000.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: true
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: true
  solver_position_iteration_count: 32
  solver_velocity_iteration_count: 1
  sleep_threshold: 0.005
  stabilization_threshold: 0.0005
  fix_root_link: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props:
  drive_type: force
  max_effort: null
  max_velocity: null
  stiffness: null
  damping: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2026-02-07 at 14:24:49.
##
